# Theme and site settings

title: "Foothills Movers"
primary_color: "#FF8C00"      # Brand orange for headings/buttons
secondary_bg_color: "#333333" # Dark background for nav/hero
accent_color: "#FF8C00"       # Accent (same as primary)
error_color: "#FF3B30"        # Danger
text_color: "#FFFFFF"         # White text on dark
border_radius: "12px"
button_radius: "50px"

# URL settings
baseurl: ""
url: "https://transamericanlogistics-websites.github.io/foothills-movers"

# Build settings
markdown: kramdown

theme: minima # not used, we embed CSS manually
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets
exclude:
  - Gemfile.lock
  - node_modules
