name: "Deploy to GitHub Pages"
on:
  push:
    branches: [ main ]
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: gh-pages
          path: gh-pages
      - name: Build site
        run: bundle exec jekyll build --destination gh-pages
      - name: Push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy site"
          git push origin gh-pages
