name: "Jekyll Build"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Build site with Jekyll
        run: bundle exec jekyll build --verbose
      - name: Archive production artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site
